export const ERROR = {
  NOT_FOUND: 'NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  USER_NOT_AUTHENTICATED: 'USER_NOT_AUTHENTICATED',
  FORBIDDEN_TO_ACCESS: 'FORBIDDEN_TO_ACCESS',
};
