exports.PRODUCT_CATEGORY = {
    all: 0,
    'watch-and-accessory': 1,
    'electronic-computer': 2,
    camera: 3,
    'house-life': 4,
    'sport-entertainment': 5,
    cultural: 6,
    fashion: 7,
    film: 8,
    music: 9,
    'health-beauty': 10,
    kid: 11,
    present: 12,
    vehicle: 13,
    'health, beauty': 14,
    game: 15,
    food: 16,
    flower: 17,
    book: 18,
    comic: 19,
    hobby: 20,
    other: 21
}
