version: '3'
services:

  nodejs:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - 3030:3030
    depends_on:
      - redis
      - mysql
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: auction
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: oke
      # MYSQL_CONNECTION_URL: mysql://root@localhost/auction

  socketjs:
    build:
      context: ./api
      dockerfile: Dockerfile-socket
    volumes:
      - ./api:/app
    ports:
      - 3031:3031
    depends_on:
      - redis
      - mysql
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: auction
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: oke
      # MYSQL_CONNECTION_URL: mysql://root@localhost/auction

  reactjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - 3000:3000

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "auction"

  # nestjs:
  #   build:
  #     context: ./api-nest
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./api-nest:/app
  #   ports:
  #     - 3131:3131
  #   depends_on:
  #     - mysql

  springboot:
    build:
      context: ./api-springboot
      dockerfile: Dockerfile
    volumes:
      - ./api-springboot:/app
    ports:
      - 8080:8080
    depends_on:
      - mysql
